### ISSUE TITLE
Invalid "Java 6 applications are prevented from being deployed" error message

### ISSUE THREAD

**Issue by marceloverdijk** [GoogleCloudPlatform/gradle-appengine-plugin#257]
It'a long time I tried appengine but I when using `gradlew appengineUpdate` I get the below "Java 6 applications are prevented from being deployed" error despite I'm using Java 7.

I also used used:

```
$ javap -verbose My.class | grep "major"
  major version: 51
```

To verify my classes are Java 7.

I'm using Gradle 2.14.1 and Appengine 1.9.40.

```
400 Bad Request
Java 6 applications are prevented from being deployed to Google App Engine from any version of the SDK, including older ones. If you need to continue to deploy Java 6 applications for compatibility reasons, you can request that your application be whitelisted for Java 6 deployment by visiting http://goo.gl/ycffXq.
```

**Comment by loosebazooka** [comment]
Yeah that looks like a pretty old code path. Perhaps you're doing something that's triggering it, but that's not the real problem. Are you using Java 8 anywhere?

**Comment by marceloverdijk** [comment]
Hi, do you think the same error is shown when using Java 8? The classes are Java 7 but my java home is indeed Java 8.... I'm using gradle.properties to set JDK7.

**Comment by marceloverdijk** [comment]
Even with `JAVA_HOME` explicitly set to JDK 7 and running Gradle with `--no-daemon` option I get the same error.

To proof this is my output for:
```
$ ./gradlew -v

------------------------------------------------------------
Gradle 2.14.1
------------------------------------------------------------

Build time:   2016-07-18 06:38:37 UTC
Revision:     d9e2113d9fb05a5caabba61798bdb8dfdca83719

Groovy:       2.4.4
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.7.0_79 (Oracle Corporation 24.79-b02)
OS:           Mac OS X 10.11.4 x86_64
```

I wonder how Google determines that it think it's running Java 6...

**Comment by loosebazooka** [comment]
Perhaps it has something to do with your configuration. Can you show us
your appengine-web.xml and build.gradle (feel free to replace anything
identifying parts)

**Comment by marceloverdijk** [comment]
Nothing to hide, here is my `build.gradle`:

```
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath "com.google.appengine:gradle-appengine-plugin:1.9.40"
    }
}

apply plugin: "java"
apply plugin: "idea"
apply plugin: "war"
apply plugin: "appengine"

ext {
    appengineVersion = "1.9.40"
    commonsLang3Version = "3.4"
    javaVersion = "1.7"
    servletVersion = "2.5"
}

repositories {
    mavenCentral()
}

dependencies {
    appengineSdk "com.google.appengine:appengine-java-sdk:${appengineVersion}"
    compile "com.google.appengine:appengine-api-1.0-sdk:${appengineVersion}"
    compile "org.apache.commons:commons-lang3:${commonsLang3Version}"
    providedCompile "javax.servlet:servlet-api:${servletVersion}"
}

appengine {
    disableUpdateCheck = true
    downloadSdk = true
    httpPort = 8088
    jvmFlags = [
            "-Ddatastore.backing_store=${projectDir}/local_db.bin"
    ]
    appcfg {
        noCookies = true
        oauth2 = true
        app {
            id = "fb-hilo-test"
        }
    }
}

clean {
    delete "local_db.bin"
}

compileJava {
    sourceCompatibility = javaVersion
    targetCompatibility = javaVersion
}

idea {
    module {
        downloadJavadoc = true
        downloadSources = true
        inheritOutputDirs = false
        outputDir = file("${buildDir}/classes/main")
        testOutputDir = file("${buildDir}/classes/test")
    }
}

task wrapper(type: Wrapper) {
    description = "Generates gradlew[.bat] scripts."
    gradleVersion = "2.14.1"
}
```

`gradle.properties` contains:

```
org.gradle.daemon=false
org.gradle.java.home=/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home
```

And my `app.yaml`:

```
application: fb-hilo-test
version: 1
runtime: java
sessions_enabled: false
threadsafe: true

handlers:
  - url: /heartbeat
    name: heartbeatServlet
    servlet: com.github.marceloverdijk.fb.hilo.servlet.HeartbeatServlet
    login: admin
  - url: /webhook
    name: webHookServlet
    servlet: com.github.marceloverdijk.fb.hilo.servlet.WebHookServlet

error_handlers:
  - file: default_error.html

static_files:
  - include: /assets/**
  - include: /default_error.html

system_properties:
  java.util.logging.config.file: WEB-INF/logging.properties
```
